### ISSUE TITLE
Error Class "IP2ProxyLaravel" not found

### ISSUE THREAD

**Issue by phpnil** [ip2location/ip2proxy-laravel#1]
PHP 8.1.11
Laravel 9.36.4
Class "IP2ProxyLaravel" not found

code ///
use IP2ProxyLaravel;

public function index()
    {
        $ip = $_SERVER['REMOTE_ADDR'];
        $records = IP2ProxyLaravel::get($ip, 'bin');
}

**Comment by ip2location-com** [comment]
Kindly check your `composer.json` whether the `ip2location/ip2proxy-laravel` package is installed. 

If it is not, run the command: `composer require ip2location/ip2proxy-laravel` to download the package.

**Comment by phpnil** [comment]
@ip2location 
in composer.json  package is installed.

```
"require": {
        "php": "^8.0.2",
        "ip2location/ip2proxy-laravel": "^1.1",
        
```

**Comment by ip2location-com** [comment]
Can you follow the steps in the [README.md](https://github.com/ip2location/ip2proxy-laravel/blob/master/README.md#usage) for the testing?

**Comment by phpnil** [comment]
I am following same step as readme.md but not working on live server.

Php Version
8.1.12

Laravel Version
9.36.4

**Comment by ip2location-com** [comment]
Could you drop us an email at support@ip2location.com about this issue and provide us with the following items in the email to ease the investigation?

- the Controller file which calling the `IP2ProxyLaravel::get` function
- the screenshots about the error message
